"use client";
import {FormEvent} from "react";
import {ArrowRight,BarChart3,Camera,Check,Code2,Globe2,Mail,MapPin,MessageCircle,Palette,Search,ShoppingBag,Sparkles,Target} from "lucide-react";

const services=[
 [Code2,"Website Design","Fast, responsive websites designed to turn visitors into enquiries."],
 [ShoppingBag,"E-commerce","Conversion-focused stores with cart, checkout and payment support."],
 [Camera,"Social Media","Consistent content, sharp creatives and practical monthly management."],
 [Target,"Meta Ads","Audience-led campaigns built for leads, reach and measurable growth."],
 [Search,"Google Ads & SEO","Show up when customers are actively searching for what you offer."],
 [Palette,"Branding","Logo systems and visual identities that make your business look credible."]
] as const;
const packages=[
 {name:"Starter Website",price:"₹4,999",note:"For a strong first presence",features:["1-page responsive website","WhatsApp & contact buttons","Basic SEO setup","7-day delivery target"]},
 {name:"Business Website",price:"₹8,999",note:"Best for growing businesses",featured:true,features:["Up to 5 professional pages","Lead/contact form","Google Map integration","Speed & SEO setup"]},
 {name:"Launch Bundle",price:"₹9,999",note:"Website + social launch",features:["1-page website","8 social media creatives","Google Business support","Brand consistency setup"]}
];
const projects=[
 {tag:"Fashion E-commerce",title:"ATTITUDE EMPIRE",text:"A bold streetwear storefront with product catalogue, cart and guided checkout.",href:"https://aslam06788.github.io/attitude-empire/"},
 {tag:"Restaurant",title:"BINODINI",text:"A polished local restaurant website built around menu discovery and reservations.",href:"https://aslam06788.github.io/binodini-restaurant/"},
 {tag:"Fitness",title:"ShaRk Gym",text:"A high-energy fitness website showcasing memberships, services and calls to action.",href:"https://aslam06788.github.io/sharkgym/"},
 {tag:"Beauty & Wellness",title:"Smart Salon",text:"A clean service-led salon experience made for local customer enquiries.",href:"https://aslam06788.github.io/smart-salon-management/"}
];
export default function Home(){
 function sendEnquiry(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const m=`Hello Avyrixa Digital!\n\nName: ${f.get("name")}\nBusiness: ${f.get("business")}\nService: ${f.get("service")}\nRequirement: ${f.get("message")}`;window.open(`https://wa.me/918609955837?text=${encodeURIComponent(m)}`,"_blank","noopener,noreferrer")}
 return <main>
  <header className="nav-wrap"><a className="brand" href="#home"><img src="/logo.png" alt=""/><span>AVYRIXA <b>DIGITAL</b></span></a><nav><a href="#services">Services</a><a href="#work">Work</a><a href="#pricing">Pricing</a><a href="#about">About</a></nav><a className="nav-cta" href="#contact">Let&apos;s talk <ArrowRight size={17}/></a></header>
  <section className="hero" id="home"><div className="orb orb-one"/><div className="orb orb-two"/><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> Digital growth partner for ambitious businesses</div><h1>Look professional.<br/><span>Grow with purpose.</span></h1><p>Websites, marketing and brand experiences that help local businesses and growing brands win more customers online.</p><div className="hero-actions"><a className="button primary" href="#contact">Start a project <ArrowRight size={18}/></a><a className="button ghost" href="#work">Explore our work</a></div><div className="trust-row"><span><Check size={15}/> Clear deliverables</span><span><Check size={15}/> Practical pricing</span><span><Check size={15}/> Direct support</span></div></div><div className="hero-visual"><div className="visual-grid"/><img src="/logo.png" alt=""/><div className="metric-card card-a"><BarChart3/><div><b>Strategy first</b><span>Built around your goal</span></div></div><div className="metric-card card-b"><Globe2/><div><b>Built to convert</b><span>Fast • Mobile • Clear</span></div></div></div></section>
  <section className="ticker"><span>WEBSITE DESIGN</span><i/><span>E-COMMERCE</span><i/><span>SOCIAL MEDIA</span><i/><span>PERFORMANCE ADS</span><i/><span>BRANDING</span></section>
  <section className="section" id="services"><div className="section-head"><div><p className="kicker">What we do</p><h2>Everything your business needs to grow online.</h2></div><p>Focused digital solutions—planned clearly, designed professionally and delivered without unnecessary complexity.</p></div><div className="service-grid">{services.map(([Icon,title,text],i)=><article className="service-card" key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section work-section" id="work"><div className="section-head"><div><p className="kicker">Selected work</p><h2>Real projects. Different industries. One standard.</h2></div><p>Each experience is shaped around the business, its audience and the action customers should take next.</p></div><div className="work-grid">{projects.map((p,i)=><a href={p.href} target="_blank" rel="noreferrer" className={`project project-${i+1}`} key={p.title}><span>{p.tag}</span><div><p>0{i+1}</p><h3>{p.title}</h3><small>{p.text}</small><b>View project <ArrowRight size={16}/></b></div></a>)}</div></section>
  <section className="section" id="pricing"><div className="section-head"><div><p className="kicker">Straightforward pricing</p><h2>Start at the level that fits your business.</h2></div><p>Every project begins with a clear scope. Final quotations depend on features, content volume and third-party costs.</p></div><div className="price-grid">{packages.map(p=><article className={`price-card ${p.featured?"featured":""}`} key={p.name}>{p.featured&&<div className="popular">Most popular</div>}<p>{p.name}</p><h3>{p.price}</h3><span>{p.note}</span><ul>{p.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><a href="#contact">Choose package <ArrowRight size={17}/></a></article>)}</div><div className="mini-prices"><span><b>Social Media</b> ₹3,999/month</span><span><b>Meta Ads Setup</b> ₹2,499</span><span><b>E-commerce Website</b> from ₹14,999</span></div></section>
  <section className="about" id="about"><div><p className="kicker">Why Avyrixa</p><h2>Small agency attention.<br/>Professional execution.</h2></div><div><p>Avyrixa Digital is a Kolkata-based digital agency helping startups, local businesses and growing brands build a stronger online presence.</p><p>We combine practical strategy, thoughtful design and clear communication—so you always know what is being built, why it matters and what happens next.</p><div className="values"><span><b>01</b> Honest scope</span><span><b>02</b> Mobile-first work</span><span><b>03</b> Clear support</span></div></div></section>
  <section className="contact" id="contact"><div className="contact-copy"><p className="kicker">Start a conversation</p><h2>Ready to move your business forward?</h2><p>Tell us what you need. We&apos;ll respond with the clearest next step.</p><div className="contact-links"><a href="https://wa.me/918609955837"><MessageCircle/> +91 8609955837</a><a href="mailto:avyrixadigital@gmail.com"><Mail/> avyrixadigital@gmail.com</a><span><MapPin/> Kolkata, West Bengal, India</span></div></div><form onSubmit={sendEnquiry}><label>Name<input required name="name" placeholder="Your name"/></label><label>Business<input required name="business" placeholder="Business or brand name"/></label><label>Service<select name="service" defaultValue="Website Design"><option>Website Design</option><option>E-commerce Website</option><option>Social Media Management</option><option>Meta Ads</option><option>Google Ads & SEO</option><option>Branding</option></select></label><label>What do you need?<textarea required name="message" rows={4} placeholder="Tell us a little about your project"/></label><button type="submit">Send via WhatsApp <ArrowRight size={18}/></button></form></section>
  <footer><a className="brand" href="#home"><img src="/logo.png" alt=""/><span>AVYRIXA <b>DIGITAL</b></span></a><p>Websites that impress. Marketing that converts.</p><span>© 2026 Avyrixa Digital</span></footer><a className="floating-wa" href="https://wa.me/918609955837" target="_blank" rel="noreferrer"><MessageCircle/></a>
 </main>
}
